name: Build and Release eLog & remeLog

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    env:
      DOTNET_VERSION: '6.0.x'

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Restore dependencies via solution
        run: dotnet restore Work.sln

      - name: 🔨 Публикация eLog
        run: dotnet publish eLog/eLog.csproj -c Release -r win-x64 -o publish/eLog --self-contained false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishReadyToRun=false

      - name: 🔨 Публикация remeLog
        run: dotnet publish remeLog/remeLog.csproj -c Release -r win-x64 -o publish/remeLog --self-contained false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishReadyToRun=false

      - name: 🧪 Проверка публикации
        run: |
          dir publish\eLog
          dir publish\remeLog

      - name: 🚀 Создание релиза и загрузка артефактов
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            publish/eLog/eLog.exe
            publish/remeLog/remeLog.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
